import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { marked } from "marked";
import { checkRateLimit, rateLimitResponse, RATE_LIMITS } from "@/lib/rate-limit";

export async function GET(req: Request) {
  try {
    const { searchParams } = new URL(req.url);
    const policyId = searchParams.get("id");

    if (!policyId) {
      return NextResponse.json(
        { error: "Policy ID is required" },
        { status: 400 }
      );
    }

    const supabase = await createClient();

    // Verify authentication
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Rate limit check
    const rateLimit = await checkRateLimit(
      supabase,
      `policy-export:${user.id}`,
      RATE_LIMITS.policyExport
    );
    if (!rateLimit.allowed) {
      return rateLimitResponse(rateLimit);
    }

    // Fetch the policy with organization check
    const { data: policy } = await supabase
      .from("policies")
      .select(
        `
        *,
        organizations!inner(user_id, name)
      `
      )
      .eq("id", policyId)
      .single();

    if (!policy) {
      return NextResponse.json({ error: "Policy not found" }, { status: 404 });
    }

    if (policy.organizations.user_id !== user.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 403 });
    }

    // Convert markdown to HTML
    const htmlContent = await marked(policy.content_markdown);

    // Create a printable HTML document
    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${policy.title}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
    
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      line-height: 1.7;
      color: #1a1a2e;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 60px;
      font-size: 11pt;
    }
    
    h1 {
      font-size: 24pt;
      font-weight: 700;
      margin-bottom: 8px;
      color: #0d9488;
      border-bottom: 2px solid #0d9488;
      padding-bottom: 16px;
    }
    
    h2 {
      font-size: 16pt;
      font-weight: 600;
      margin-top: 32px;
      margin-bottom: 12px;
      color: #0d9488;
      page-break-after: avoid;
    }
    
    h3 {
      font-size: 13pt;
      font-weight: 600;
      margin-top: 20px;
      margin-bottom: 8px;
      page-break-after: avoid;
    }
    
    h4 {
      font-size: 11pt;
      font-weight: 600;
      margin-top: 16px;
      margin-bottom: 6px;
    }
    
    p {
      margin-bottom: 12px;
    }
    
    ul, ol {
      margin-bottom: 12px;
      padding-left: 24px;
    }
    
    li {
      margin-bottom: 6px;
    }
    
    strong {
      font-weight: 600;
    }
    
    blockquote {
      border-left: 3px solid #0d9488;
      padding-left: 16px;
      margin: 16px 0;
      color: #64748b;
      font-style: italic;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 16px 0;
      font-size: 10pt;
    }
    
    th, td {
      border: 1px solid #e2e8f0;
      padding: 8px 12px;
      text-align: left;
    }
    
    th {
      background-color: #f1f5f9;
      font-weight: 600;
    }
    
    hr {
      border: none;
      border-top: 1px solid #e2e8f0;
      margin: 24px 0;
    }
    
    code {
      background-color: #f1f5f9;
      padding: 2px 6px;
      border-radius: 4px;
      font-family: 'SF Mono', Monaco, monospace;
      font-size: 10pt;
    }
    
    pre {
      background-color: #f1f5f9;
      padding: 16px;
      border-radius: 8px;
      overflow-x: auto;
      margin: 16px 0;
    }
    
    pre code {
      background: none;
      padding: 0;
    }
    
    .header {
      text-align: center;
      margin-bottom: 40px;
    }
    
    .meta {
      text-align: center;
      color: #64748b;
      font-size: 10pt;
      margin-top: 8px;
    }
    
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e2e8f0;
      text-align: center;
      color: #64748b;
      font-size: 9pt;
    }
    
    @media print {
      body {
        padding: 0;
      }
      
      h2, h3 {
        page-break-after: avoid;
      }
      
      ul, ol, table {
        page-break-inside: avoid;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${policy.title}</h1>
    <p class="meta">
      ${policy.organizations.name} • Version ${policy.version} • Generated ${new Date(policy.generated_at).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
    </p>
  </div>
  
  ${htmlContent}
  
  <div class="footer">
    <p>Generated by OpenGuard • AI-Powered Cybersecurity for Non-Profits</p>
    <p>This policy should be reviewed annually and updated as your organization's needs change.</p>
  </div>
  <script>window.onload = function() { window.print(); };</script>
</body>
</html>
    `;

    // Return HTML with print-friendly headers
    return new NextResponse(html, {
      headers: {
        "Content-Type": "text/html",
        "Content-Disposition": `inline; filename="${policy.title.replace(/[^a-zA-Z0-9]/g, "_")}.html"`,
      },
    });
  } catch (error) {
    console.error("PDF export error:", error);
    return NextResponse.json(
      { error: "Failed to export policy" },
      { status: 500 }
    );
  }
}
